version: "3.3"

services:
  frontend:
    build: ./frontend
    ports:
      - 8080:80
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    build: ./backend
    networks:
      - internal
    depends_on:
      - database
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
  database:
    image: postgres:13
    networks:
      - internal
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    security_opt:
      - no-new-privileges:true
  redis:
    image: redis:alpine3.19
    restart: unless-stopped
    sysctls:
      net.core.somaxconn: 1024
networks:
  internal:
    driver: bridge
