"""add_medicine_and_equipment_table

Revision ID: 19fdd9540637
Revises: 7fe4bc5d253b
Create Date: 2024-05-06 16:18:45.720436+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19fdd9540637'
down_revision: Union[str, None] = '7fe4bc5d253b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Containers table
    op.create_table('containers',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('import_date', sa.Date(), nullable=True),
        sa.Column('import_quantity', sa.Integer(), nullable=True),
        sa.Column('details', sa.String(), nullable=True),
        sa.Column('container_type', sa.Enum('MEDICINE', 'EQUIPMENT', name='containertype'), nullable=True),
        sa.Column('container_price', sa.Integer(), nullable=True),
        sa.Column('price_per_unit', sa.Integer(), nullable=True),
        sa.Column('manufacturer', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Medicines table
    op.create_table('medicines',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Equipments table
    op.create_table('equipments',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('availability', sa.Integer(), nullable=True),
        sa.Column('maintanance_history', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # MedicineBatch table
    op.create_table('medicine_batches',
        sa.Column('expiration_date', sa.Date(), nullable=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('medicine_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['containers.id'], ),
        sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # EquipmentBatch table
    op.create_table('equipment_batches',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('equipment_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['containers.id'], ),
        sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipments')
    op.drop_table('medicines')
    op.drop_table('equipment_batches')
    op.drop_table('medicine_batches')
    op.drop_table('containers')
    # ### end Alembic commands ###
