"""add other employee type

Revision ID: 25946c426a79
Revises: d59b0ba1d480
Create Date: 2024-04-09 13:46:42.456204+07:00

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '25946c426a79'
down_revision: Union[str, None] = 'd59b0ba1d480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TYPE employeetype ADD VALUE 'OTHER'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TYPE employeetype DROP VALUE 'OTHER'
    """)
    # ### end Alembic commands ###
