"""seed-data

Revision ID: 675a4bf03c4a
Revises: 19fdd9540637
Create Date: 2024-05-19 21:25:31.018417+07:00

"""
from typing import Sequence, Union
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '675a4bf03c4a'
down_revision: Union[str, None] = '19fdd9540637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO users (id, ssn, phone_number, birth_date, gender, health_insurance, last_name, first_name, address, email, username, password, role) VALUES 
        ('980b8598-c4f7-4ad4-8736-609be91b1934', '123456784', '0123456784', '1982-01-01', 'male', '123456784', 'Nguyễn Như', 'Thủy', '268 Ngo Quyen', 'nguyennthuy@gmail.com', 'employee3', 'b8208d02f22e9fd7da3ada78e85d1ecb6efbe2fc2febe77f5404f11408da0744', 'employee:employeetype.doctor'),
        ('f643133d-0a99-4a7d-9cdd-b771de636a84', '123456785', '0123456785', '1990-01-01', 'female', '123456785', 'Lê Thị', 'Mỹ', '219 Ly Thuong Kiet', 'lethimy@gmail.com', 'employee4', '9bc4cfaadd411a7a677e6dde8d582a202c8866aa04d8e1eed9fc54b07b399845', 'employee:employeetype.nurse'),
        ('fd158827-8813-4be5-8983-cc5f1dd1e8d6', '123456786', '0123456786', '1998-01-01', 'male', '123456786', 'Ngô Văn', 'Tùng', '8 Nguyen Tri Phuong', 'ngovantung@gmail.com', 'employee5', '6a3c4b4d750947b4eabf9d083d9bb7986ad4f54cdeb5bfa3f553d636a0f46c16', 'employee:employeetype.manager'),
        ('b6113e94-e0bb-4b69-81cb-cbf9863981db', '123456787', '0123456787', '1992-01-01', 'female', '123456787', 'Hoàng Thị', 'Châu', '28 Au Co', 'hoangthichau@gmail.com', 'employee6', '3596954b8efcb2698bedbc4d49b4ca5704331051e501cf5248694cf8d60223c6', 'employee:employeetype.other'),
        ('3b8c457a-9cb9-4e54-bc4e-0ad7e818b349', '123456788', '0123456788', '1993-01-01', 'male', '123456788', 'Châu Văn', 'Bảo', '293 Hoang Sa', 'chauvanbao@gmail.com', 'employee7', 'd435fc77f7556996dda5340d0410c2f723e21ec8d4d545063725f075dc1f6867', 'employee:employeetype.doctor'),
        ('c5af7fd2-0eaf-4da0-8cf3-15b3619112b1', '123456778', '0123456789', '1982-01-01', 'female', '123456789', 'Lê Thị', 'Tiên', '232 Truong Sa', 'lttien@gmail.com', 'employee8', '672e93f8e0ae97bd7e6648d5ab3d06302086265adb94880887ac2372e08be12c', 'employee:employeetype.nurse'),
        ('330393df-2378-4a4e-a74c-51880dfd19a4', '123456792', '0123456780', '1978-01-01', 'male', '123456780', 'Nguyễn Văn', 'An', '103 Ngo Quyen', 'ngvanan@gmail.com', 'employee9', '4765ccede64288894bdeac138d6b179b73ed59700da711f295d1b066c5fb7601', 'employee:employeetype.manager'),
        ('382d1947-71d1-4533-964d-22daa2a99c40', '123456781', '0123456781', '1980-01-01', 'female', '123456781', 'Nguyễn Thị', 'Sương', '8 Hung Vuong', 'nguyenvans@gmail.com', 'employee10', '604c0a454d7e31831cdc9244c3a2bdca296a81756bcc32f7814fc77587d72490', 'employee:employeetype.other'),
        ('c0f498d2-842d-4fca-9f04-eb1f7e045503', '123456782', '0123456782', '1989-01-01', 'male', '123456782', 'Trương Đức', 'Hào', '26 Ho Dac Di', 'trgduchao@gmail.com', 'employee11', '7683eaeb63feabf983b78228a721cde5200f76a7ae7179f3cfbd2d05a081e1ea', 'employee:employeetype.doctor'),
        ('d89a8780-98f2-45de-8522-a048b36beb9e', '123456765', '0123456783', '2000-01-01', 'female', '123456783', 'Nguyễn Thị', 'Như', '92 Ly Thuong Kiet', 'nguyenthinhu@gmail.com', 'employee12', '395ec032d4c97beac70873c4796f13bc7a6751bb26b6a0f1aa53b55f2ccd6ffc', 'employee:employeetype.nurse');
        
        INSERT INTO employees (user_id, employee_type, education_level, begin_date, end_date, faculty) VALUES
        ('980b8598-c4f7-4ad4-8736-609be91b1934', 'DOCTOR', 'MASTER', '2020-01-01', '2024-12-01', 'Gây mê'),
        ('f643133d-0a99-4a7d-9cdd-b771de636a84', 'NURSE', 'BACHELOR', '2020-01-01', '2024-12-01', 'Khám lồng ngực'),
        ('fd158827-8813-4be5-8983-cc5f1dd1e8d6', 'MANAGER', 'MASTER', '2020-01-01', '2024-12-01', 'Tim mạch'),
        ('b6113e94-e0bb-4b69-81cb-cbf9863981db', 'OTHER', 'UNDERGRADUATE', '2020-01-01', '2024-12-01', 'Hỗ trợ người già'),
        ('3b8c457a-9cb9-4e54-bc4e-0ad7e818b349', 'DOCTOR', 'MASTER', '2020-01-01', '2024-12-01', 'Chăm sóc đặc biệt'),
        ('c5af7fd2-0eaf-4da0-8cf3-15b3619112b1', 'NURSE', 'DOCTOR', '2020-01-01', '2024-12-01', 'Dịch vụ chung'),
        ('330393df-2378-4a4e-a74c-51880dfd19a4', 'MANAGER', 'MASTER', '2020-01-01', '2024-12-01', 'Phẫu thuật tổng quát'),
        ('382d1947-71d1-4533-964d-22daa2a99c40', 'MANAGER', 'BACHELOR', '2020-01-01', '2024-12-01', 'Huyết học'),
        ('c0f498d2-842d-4fca-9f04-eb1f7e045502', 'OTHER', 'UNKNOWN', '2020-01-01', '2024-12-01', 'Sức khỏe cộng đồng'),
        ('d89a8780-98f2-45de-8522-a048b36beb9e', 'NURSE', 'DOCTOR', '2020-01-01', '2024-12-01', 'Thần kinh');
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass

