"""change way employee handle patient

Revision ID: 93ef6f9e7479
Revises: 957e0bfd7120
Create Date: 2024-04-14 19:08:42.427380+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ef6f9e7479'
down_revision: Union[str, None] = '957e0bfd7120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('in_charge_of_patients', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('in_charge_of_patients', 'progress_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('in_charge_of_patients', 'progress_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('in_charge_of_patients', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
