"""fix patient progress schedule

Revision ID: 957e0bfd7120
Revises: 25946c426a79
Create Date: 2024-04-14 16:07:08.213323+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957e0bfd7120'
down_revision: Union[str, None] = '25946c426a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_progresses', sa.Column(
        'start_treatment', sa.DateTime(), nullable=True))
    op.add_column('patient_progresses', sa.Column(
        'end_treatment', sa.DateTime(), nullable=True))
    op.drop_column('patient_progresses', 'duration')
    op.drop_column('patient_progresses', 'treatment_type')
    op.drop_column('patient_progresses', 'treatment_schedule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_progresses', sa.Column(
        'treatment_schedule', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_progresses', sa.Column(
        'treatment_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_progresses', sa.Column(
        'duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('patient_progresses', 'end_treatment')
    op.drop_column('patient_progresses', 'start_treatment')
    # ### end Alembic commands ###
