"""seed employee

Revision ID: ae8e99277c90
Revises: 9a3655547f18
Create Date: 2024-04-02 20:10:44.426666+07:00

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ae8e99277c90'
down_revision: Union[str, None] = '9a3655547f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE EXTENSION pgcrypto;
        INSERT INTO users (id, ssn, phone_number, birth_date, gender, health_insurance, last_name, first_name, nation, province, city, address, email, username, password, role) VALUES 
        ('189a8780-98f2-45de-8522-a048b36beb9e', '123456789', '0123456789', '2000-01-01', 'male', '123456789', 'Nguyễn Văn', 'A', 'Vietnam', 'Hanoi', 'Hanoi', '268 Ly Thuong Kiet', 'nguyenvana@gmail.com', 'employee1', '18124aeeecee69daf749c1d96bc0eacc331c78f520533180fbf14fce0824450a', 'EMPLOYEE'),
        ('289a8780-98f2-45de-8522-a048b36beb9e', '123456780', '0123456780', '2000-01-01', 'female', '123456780', 'Nguyễn Thị', 'B', 'Vietnam', 'Hanoi', 'Hanoi', '268 Ly Thuong Kiet', 'nguyenvanb@gmail.com', 'employee2', 'de08da8c83b62313f3cb789d6fd46fa2621b71113a754ecf8f422504ac977f94', 'EMPLOYEE'),
        ('389a8780-98f2-45de-8522-a048b36beb9e', '123456781', '0123456781', '2000-01-01', 'male', '123456781', 'Trần Văn', 'C', 'Vietnam', 'Ho Chi Minh', 'Ho Chi Minh', '123 Le Loi', 'tranvanc@gmail.com', 'employee3', 'e39e75f81a243f8c58648b15620973a89150835107374ca663533414bf0d68d7', 'EMPLOYEE'),
        ('489a8780-98f2-45de-8522-a048b36beb9e', '123456782', '0123456782', '2000-01-01', 'female', '123456782', 'Trần Thị', 'D', 'Vietnam', 'Ho Chi Minh', 'Ho Chi Minh', '123 Le Loi', 'tranvand@gmail.com', 'employee4', 'cd1d0aaa4215d811dcef391dcec9bc46f4619e7316faa31a8962905dbaf97b88', 'EMPLOYEE');
        
INSERT INTO users (id, ssn, phone_number, birth_date, gender, health_insurance, last_name, first_name, nation, province, city, address, email, username, password, role) VALUES 
    ('589a8780-98f2-45de-8522-a048b36beb9e', '223456783', '0123456783', '2000-01-01', 'male', '123456783', 'Lê Văn', 'E', 'Vietnam', 'Hanoi', 'Hanoi', '268 Ly Thuong Kiet', 'levane@gmail.com', 'patient1', encode(digest(concat('password1', 'patient1'), 'sha256'), 'hex'), 'PATIENT'),
    ('689a8780-98f2-45de-8522-a048b36beb9e', '223456784', '0123456784', '2000-01-01', 'female', '123456784', 'Lê Thị', 'F', 'Vietnam', 'Hanoi', 'Hanoi', '268 Ly Thuong Kiet', 'levanf@gmail.com', 'patient2', encode(digest(concat('password2', 'patient2'), 'sha256'), 'hex'), 'PATIENT'),
    ('789a8780-98f2-45de-8522-a048b36beb9e', '223456785', '0123456785', '2000-01-01', 'male', '123456785', 'Phạm Văn', 'G', 'Vietnam', 'Ho Chi Minh', 'Ho Chi Minh', '123 Le Loi', 'phamvang@gmail.com', 'patient3', encode(digest(concat('password3', 'patient3'), 'sha256'), 'hex'), 'PATIENT'),
    ('889a8780-98f2-45de-8522-a048b36beb9e', '223456786', '0123456786', '2000-01-01', 'female', '123456786', 'Phạm Thị', 'H', 'Vietnam', 'Ho Chi Minh', 'Ho Chi Minh', '123 Le Loi', 'phamthih@gmail.com', 'patient4', encode(digest(concat('password4', 'patient4'), 'sha256'), 'hex'), 'PATIENT'),
    ('989a8780-98f2-45de-8522-a048b36beb9e', '223456787', '0123456787', '2000-01-01', 'male', '123456787', 'Hoàng Văn', 'I', 'Vietnam', 'Hanoi', 'Hanoi', '268 Ly Thuong Kiet', 'hoangvani@gmail.com', 'patient5', encode(digest(concat('password5', 'patient5'), 'sha256'), 'hex'), 'PATIENT'),
    ('a89a8780-98f2-45de-8522-a048b36beb9e', '223456788', '0123456788', '2000-01-01', 'female', '123456788', 'Hoàng Thị', 'K', 'Vietnam', 'Hanoi', 'Hanoi', '268 Ly Thuong Kiet', 'hoangthik@gmail.com', 'patient6', encode(digest(concat('password6', 'patient6'), 'sha256'), 'hex'), 'PATIENT'),
    ('b89a8780-98f2-45de-8522-a048b36beb9e', '223456789', '0123456789', '2000-01-01', 'male', '123456789', 'Trần Văn', 'L', 'Vietnam', 'Ho Chi Minh', 'Ho Chi Minh', '123 Le Loi', 'tranvanl@gmail.com', 'patient7', encode(digest(concat('password7', 'patient7'), 'sha256'), 'hex'), 'PATIENT'),
    ('c89a8780-98f2-45de-8522-a048b36beb9e', '223456780', '0123456780', '2000-01-01', 'female', '123456780', 'Trần Thị', 'M', 'Vietnam', 'Ho Chi Minh', 'Ho Chi Minh', '123 Le Loi', 'tranthim@gmail.com', 'patient8', encode(digest(concat('password8', 'patient8'), 'sha256'), 'hex'), 'PATIENT'),
    ('d89a8780-98f2-45de-8522-a048b36beb9e', '223456781', '0123456781', '2000-01-01', 'male', '123456781', 'Nguyễn Văn', 'N', 'Vietnam', 'Hanoi', 'Hanoi', '268 Ly Thuong Kiet', 'nguyenvann@gmail.com', 'patient9', encode(digest(concat('password9', 'patient9'), 'sha256'), 'hex'), 'PATIENT'),
    ('e89a8780-98f2-45de-8522-a048b36beb9e', '223456782', '0123456782', '2000-01-01', 'female', '123456782', 'Nguyễn Thị', 'O', 'Vietnam', 'Hanoi', 'Hanoi', '268 Ly Thuong Kiet', 'nguyenvano@gmail.com', 'patient10', encode(digest(concat('password10', 'patient10'), 'sha256'), 'hex'), 'PATIENT');
        
        INSERT INTO employees (user_id, employee_type, education_level, begin_date, end_date, faculty) VALUES
        ('189a8780-98f2-45de-8522-a048b36beb9e', 'DOCTOR', 'UNKNOWN', '2020-01-01', '2024-12-01', 'Hanoi Medical University'),
        ('289a8780-98f2-45de-8522-a048b36beb9e', 'NURSE', 'BACHELOR', '2020-01-01', '2024-12-01', 'Hanoi Medical University'),
        ('389a8780-98f2-45de-8522-a048b36beb9e', 'MANAGER', 'MASTER', '2020-01-01', '2024-12-01', 'Hanoi Medical University'),
        ('489a8780-98f2-45de-8522-a048b36beb9e', 'MANAGER', 'UNDERGRADUATE', '2020-01-01', '2024-12-01', 'Hanoi Medical University');
        
        INSERT INTO patients (user_id, weight, height, note) VALUES
        ('589a8780-98f2-45de-8522-a048b36beb9e', 60, 180, 'Healthy'),
        ('689a8780-98f2-45de-8522-a048b36beb9e', 70, 165, 'Healthy'),
        ('789a8780-98f2-45de-8522-a048b36beb9e', 80, 160, 'Healthy'),
        ('889a8780-98f2-45de-8522-a048b36beb9e', 90, 175, 'Healthy'),
        ('989a8780-98f2-45de-8522-a048b36beb9e', 45, 167, 'Healthy'),
        ('a89a8780-98f2-45de-8522-a048b36beb9e', 56, 170, 'Healthy'),
        ('b89a8780-98f2-45de-8522-a048b36beb9e', 77, 168, 'Healthy'),
        ('c89a8780-98f2-45de-8522-a048b36beb9e', 86, 183, 'Healthy'),
        ('d89a8780-98f2-45de-8522-a048b36beb9e', 56, 164, 'Healthy'),
        ('e89a8780-98f2-45de-8522-a048b36beb9e', 65, 165, 'Healthy');
        
        INSERT INTO medical_records (id, patient_id) VALUES
        (1, '589a8780-98f2-45de-8522-a048b36beb9e'),
        (2, '689a8780-98f2-45de-8522-a048b36beb9e'),
        (3, '789a8780-98f2-45de-8522-a048b36beb9e'),
        (4, '889a8780-98f2-45de-8522-a048b36beb9e'),
        (5, '989a8780-98f2-45de-8522-a048b36beb9e'),
        (6, 'a89a8780-98f2-45de-8522-a048b36beb9e'),
        (7, 'b89a8780-98f2-45de-8522-a048b36beb9e'),
        (8, 'c89a8780-98f2-45de-8522-a048b36beb9e'),
        (9, 'd89a8780-98f2-45de-8522-a048b36beb9e'),
        (10, 'e89a8780-98f2-45de-8522-a048b36beb9e');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
