"""add user table

Revision ID: eed208884cf6
Revises: 
Create Date: 2024-03-19 15:39:07.269100+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from util.crypto import hash_password
import uuid

# revision identifiers, used by Alembic.
revision: str = 'eed208884cf6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table('users',
                                  sa.Column('id', sa.UUID, nullable=False),
                                  sa.Column('username', sa.String(),
                                            nullable=False),
                                  sa.Column('password', sa.String(), nullable=False))
    op.bulk_insert(users_table, [
        {
            'id': str(uuid.uuid4()),
            'username': 'guest1',
            'password': hash_password("guest1", "guest1")
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
