"""init db

Revision ID: fb499768fa17
Revises: 
Create Date: 2024-04-02 19:51:54.818003+07:00

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'fb499768fa17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
