name: Linter Backend
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest 
    if:
      startsWith(github.event.pull_request.head.ref, 'backend/')
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: "./backend"
