name: Linter
on: [ pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: chartboost/ruff-action@v1
        with:
<<<<<<< HEAD
          args: check .
          fix_args: fix .
=======
          args: --check .
          fix_args: --fix .
          config: .ruff.toml
>>>>>>> origin/main
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style fixes by ruff'
